plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "me.shedaniel.unified-publishing"
}

configurations {
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation("dev.boxadactle:Boxlib-fabric:${rootProject.boxlib_version}") { transitive = false }

    include (implementation "net.lingala.zip4j:zip4j:$rootProject.zip4j_version")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}


processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

import groovy.json.JsonSlurper
import groovy.json.JsonOutput

// someone pls make this work like its suppposed to
tasks.named('processResources') {
    doLast {
        def jsonFile = file("$buildDir/resources/main/mcshare.mixins.json")

        if (jsonFile.exists()) {
            def jsonSlurper = new JsonSlurper()
            def data = jsonSlurper.parse(jsonFile)

            data["refmap"] = "${mod_id}.refmap.json"

            jsonFile.text = JsonOutput.prettyPrint(JsonOutput.toJson(data))
        } else {
            println "mixin config not found at ${jsonFile}"
        }
    }
}

unifiedPublishing {
    project {
        displayName = "[Fabric ${rootProject.minecraft_version}] v$rootProject.version"
        version = "$rootProject.version-fabric"
        changelog = "A changelog can be found here: https://github.com/Boxadactle/MCShare/releases/tag/$rootProject.version"
        releaseType = rootProject.release_type
        gameVersions = Arrays.asList(rootProject.game_versions.split(","))
        gameLoaders = [ "fabric", "quilt" ]
        relations {
            it.depends {
                it.curseforge = "boxlib"
                it.modrinth = "boxlib"
            }
        }

        mainPublication tasks.remapJar

        var cfToken = System.getenv("CURSEFORGE_TOKEN")
        if (cfToken != null) {
            curseforge {
                token = cfToken
                id = rootProject.project_id_curseforge
            }
        }

        var modrinthToken = System.getenv("MODRINTH_TOKEN")
        if (modrinthToken != null) {
            modrinth {
                token = modrinthToken
                id = rootProject.project_id_modrinth
                version = "${rootProject.version}-fabric"
            }
        }
    }
}