plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "me.shedaniel.unified-publishing"
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    implementation "dev.boxadactle:Boxlib-neoforge:$rootProject.boxlib_version"

    implementation "net.lingala.zip4j:zip4j:$rootProject.zip4j_version"

    jarJar(implementation "net.lingala.zip4j:zip4j:$rootProject.zip4j_version")
    additionalRuntimeClasspath "net.lingala.zip4j:zip4j:$rootProject.zip4j_version"
}

unifiedPublishing {
    project {
        displayName = "[NeoForge ${rootProject.minecraft_version}] v$rootProject.version"
        version = "$rootProject.version-neoforge"
        changelog = "A changelog can be found here: https://github.com/Boxadactle/DebugKeybind/releases/tag/$rootProject.version"
        releaseType = rootProject.release_type
        gameVersions = Arrays.asList(rootProject.game_versions.split(","))
        gameLoaders = [ "neoforge" ]
        relations {
            it.depends {
                it.curseforge = "boxlib"
                it.modrinth = "boxlib"
            }
        }

        mainPublication tasks.jar

        var cfToken = System.getenv("CURSEFORGE_TOKEN")
        if (cfToken != null) {
            curseforge {
                token = cfToken
                id = rootProject.project_id_curseforge
            }
        }

        var modrinthToken = System.getenv("MODRINTH_TOKEN")
        if (modrinthToken != null) {
            modrinth {
                token = modrinthToken
                id = rootProject.project_id_modrinth
                version = "${rootProject.version}-neoforge"
            }
        }
    }
}